# ************************************************************分割线************************************************************

server:
  port: 80
  undertow:
    max-http-post-size: -1 # post内容的最大值，-1代表无限大
    buffer-size: 512
    direct-buffers: true # 是否分配直接内存
    threads:
      io: 8 # 默认1核心1线程
      worker: 256 # 阻塞任务线程池
