# ************************************************************分割线************************************************************

server:
  port: 80 # 启动端口号

# 模板引擎
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: request
