# ************************************************************分割线************************************************************

server:
  port: 8080 # 启动端口号

# FreeMarker
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates