# ************************************************************分割线************************************************************

server:
  port: 80

# FreeMarker
spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
