# ************************************************************分割线************************************************************

server:
  port: 80 # 启动端口号
  tomcat:
    max-http-post-size: 1024MB # POST请求超长字符串（Java中切换Eclipse编译器）

spring:
  # 模板引擎
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .ftl
  # 数据库
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/untitled?useSSL=false&characterEncoding=utf-8
      username: root
      password: 2468
      driver-class-name: com.mysql.cj.jdbc.Driver
      # Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  servlet:
    multipart:
      max-file-size: 1024MB # 上传文件最大尺寸