# ************************************************************分割线************************************************************

server:
  port: 80 # 启动端口号

# 模板引擎
spring:
  mvc:
    view:
      prefix: classpath:/templates
      suffix: .ftl