# ************************************************************分割线************************************************************

server:
  port: 80

spring:
  application:
    name: log

logging:
  config: classpath:logback.xml
