apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    name: springboot-pod # 需要和pod label name相同
  ports:
    - port: 80 # 镜像端口（以-开头的配置不能放最后，否则无法解析）
    nodePort: 8080 # 节点端口