apiVersion: v1
kind: ReplicationController
metadata:
  name: springboot-rc
spec:
  replicas: 1 # 同时运行的Pod数量
  selector:
    name: springboot-pod
  template:
    metadata:
      labels:
        name: springboot-pod # 需要和spec.selector.name相同
    spec:
      volumes:
        - name: "host-time"
        hostPath:
          path: "/etc/localtime"
      containers:
        - name: springboot-docker
        image: springboot # 镜像名
        volumeMounts:
          - mountPath: "/etc/localtime"
          name: "host-time" # 把宿主机的时间文件挂载到容器下（Windows Docker/Alpine发行版无效）
        ports:
          - containerPort: 80