# ************************************************************分割线************************************************************

server:
  port: 80
  tomcat:
    max-http-form-post-size: 1024MB

spring:
  # FreeMarker
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates

## SSL
#server.ssl.key-alias=test
#server.ssl.key-password=123456
#server.ssl.key-store=classpath:test.jks
#server.ssl.key-store-provider=SUN
#server.ssl.key-store-type=JKS
