# ************************************************************分割线************************************************************

server:
  port: 80 # 启动端口号

spring:
  # FreeMarker
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates
  # 数据库
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/untitled?useSSL=false&characterEncoding=utf-8
      username: root
      password: 2468
      driver-class-name: com.mysql.cj.jdbc.Driver
      # Druid监控
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  # Quartz
  quartz:
    job-store-type: jdbc # 定时任务存储在数据库中
    properties:
      org:
        quartz:
          scheduler: # 调度器
            instanceName: springboot_task
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool: # 线程池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
