# ************************************************************分割线************************************************************
# ①同时存在yaml/yml和properties时，优先使用properties

server:
  port: 80

spring:
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates

# 实体类
model:
  user:
    id: 1
    name: name1
    password: ${model.user.name}${model.user.id}

custom:
  flag: str123
